name: Build package
run-name: Build package
on:
  push:
    branches: 
      - main
    tags:
      - v*
jobs:
  Deploy-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Exit if not main branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1
      - run: "npm run build"
      - run: "cp package.json dist/package.json"
      - run: "echo \"//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_KEY }}\" > ~/.npmrc"
      - run: "cd dist && npm publish --dry-run --access public"