name: Build package
run-name: Build package
on:
  push:
    tags:
      - v*
jobs:
  Run-Tests:
    uses: ./.github/workflows/test.yml
  Deploy-Package:
    runs-on: ubuntu-latest
    needs: Run-Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - run: "npm install"
      - run: "npm run build"
      - run: "cp package.json dist/package.json"
      - run: "cp README.md dist/README.md"
      - run: "echo \"//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_KEY }}\" > ~/.npmrc"
      - run: "cd dist && npm publish --access public"